### ISSUE TITLE
MITBC - Replaced Contracts

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#60] opened 2017-07-31 14:56 UTC
Based on the documentation I've reviewed, replacedContracts should be optional, but in testing MITBC validations, I'm getting errors indicating those tags are expected and required.

**Comment by GihaVillazon-REISys** [comment] 2017-08-02 02:04
Please share the test file and the generated error as we are unable to reproduce the issue. 
agnecyReplacedContractsId is an optional field. 

Thank you.

**Comment by courtneycorwin** [comment] 2017-08-02 17:34
Since this is a public site, I'm not able to post the test file I've been using (I use live data). Is there an email address I can send it to?

**Comment by GihaVillazon-REISys** [comment] 2017-08-02 18:50
Please use the helpdesk email: itdashboardsupport@omb.eop.gov 

Thank You.

**Comment by TsitsiL** [comment] 2017-08-03 15:43
Good morning Courtney,

Looking at the input file, it looks like line 201 needs to be in lower tag, specifically:

•	Text on line 201: <businessCase-update:isActive>active</businessCase-update:Active> should be at the same tag level as line 198 (it should be INSIDE the addAcquisition node)

I am also suspecting that you might have to do the same for text in line 202: </businessCase-update:addAcquisition, move it to the lower tag level (at the level that 201 currently is)

Please try these changes and resubmit and let me know if it works?

Thanks!

**Comment by courtneycorwin** [comment] 2017-08-03 15:55
Hi TsiTsi!

I sent you an email with a screenshot showing that the isActive tag is inside the the addAcquisition node.

I'll wait for your response.  Thanks!!
Courtney

**Comment by TsitsiL** [comment] 2017-08-03 19:35
Hi Courtney! I saw your emails and I am currently consulting with QA team to research of this is an issue. I will update you as soon as I know more.

**Comment by TsitsiL** [comment] 2017-08-03 20:34
Courtney,

QA team's response on this:
_She is submitting isActive within the addAcquistion section, but there is no isActive element in that section.  This line must be removed.

Based on her XML file, it looks like this might be for FY19.  If it is, the submission isn't going to work on myuat-2019 because the IT Portfolio doesn't exist for 2019._

Please retry submission as advised if you are trying the submission in production. If in UAT, the submission will not work.

Please let me know either way. Thanks!

**Comment by courtneycorwin** [comment] 2017-08-03 20:35
Fantastic!  Thank you for the follow up.

**Comment by TsitsiL** [comment] 2017-08-03 21:34
I will go ahead a close this issue. If courtney still has issues we can re-oopen it.

**Closed by TsitsiL** 2017-08-03 21:34 UTC
