### ISSUE TITLE
Analysis Conclusion Not Saving Accurately

### ISSUE THREAD

**Issue by murrayalex** [ombegov/ITDB-schema#186] opened 2017-09-14 20:44 UTC
Name: Alex Murray
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Critical
Description of Issue: After a successful submission of the Analysis Conclusion node, a subsequent Get operation returns the node, but it is populated with data for the Analysis Results field. I will send both the Update Request/Response and the Get files.

**Comment by GihaVillazon** [comment] 2017-09-14 22:47
Hi Alex, 

We have a Jira ticket #924 to have the issue resolved in the 09B Sprint.

Thank You.

**Comment by murrayalex** [comment] 2017-09-15 12:15
Thanks, Giha. Given that the release date for this is outside the window, can you verify that our request file is being saved properly so we can communicate this to Agencies?

**Comment by TsitsiL** [comment] 2017-09-15 12:55
Hi Alex,
Your data is being saved. The issue is only with the response operation not retrieving the data correctly from our database. The fix will be on this operation. 
Thanks!

**Comment by TsitsiL** [comment] 2017-09-15 17:58
Closing this issue since the data is being correctly saved. The issue of the response file not having the correct information is covered in issue #173.

**Closed by TsitsiL** 2017-09-15 17:58 UTC
