### ISSUE TITLE
UAT Dashbaord Down

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#228] opened 2018-01-22 18:57 UTC
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: Is the UAT Dashboard currently down? Or, is OMB performing maintenance on the site? I am receiving the following response on a valid Get request.

> {"ok":false,"error":true,"metadata":null,"httpStatusCode":501,"httpStatusMessage":"Not Implemented","responseTime":0.049532175064087,"result":null,"errors":[{"code":501,"message":"This route is currently disabled"}]}

**Comment by TsitsiL** [comment] 2018-01-22 21:56
Thanks Ryan for reporting this issue to the helpdesk as well, as I responded there, we had disabled the submission routes to UAT and production this afternoon. They have since been re-enabled and as you confirmed, UAT is accepting your submissions again. Closing this ticket. Please let us know if you have any questions/issues. Thanks!

**Closed by TsitsiL** 2018-01-22 21:56 UTC
