### ISSUE TITLE
Validation of Eliminated/Reduced Investment table issue

### ISSUE THREAD

**Issue by barrypannell** [ombegov/ITDB-schema#178] opened 2017-09-12 16:41 UTC
Submitter: Barry Pannell
Org: DHS/MBC
Issue: We have 2 continuing investments that we are attempting to update.  Last year these investments identified other investments that were being 'eliminated/reduced' as a result of the investment work.  This year some of those investments are no longer on the IT Portfolio so they can not be referenced in the Reduced/Eliminated Investments table.  I am trying to deactivate them but validation says that the UII does not exist in the IT Portfolio so I am getting a validation error.  
Will send along a test file shortly. 
I also tried removing the 'deactivation' from the file but it still failed.  

Recommendation: Do not validate the UII on a deactivation activity.  

Will take a work around if one is available.

**Comment by barrypannell** [comment] 2017-09-12 16:58
Here is the text of the error message:

•alertInvestment 024-000005664: operations failed◦updateInvestment: 
alertThe Affected Investment UII was not found in the IT Portfolio.

•alertInvestment 024-000007547: operations failed◦updateInvestment: 
◾alertThe Affected Investment UII was not found in the IT Portfolio.

**Comment by GihaVillazon** [comment] 2017-09-12 17:04
Hi Barry, 

If the investments were eliminated last year, they will not be active or available for any edits this year. 
Therefore the validation error is correct. 

Thank You.

**Comment by barrypannell** [comment] 2017-09-12 17:54
Sorry - the investments that are in the reduced/eliminated table were dropped from the IT Portfolio this year(yesterday).  They were valid last year.  I am trying to 'remove/deactivate' them from the continuing investment business case.  It cannot.  It seems to be validating the UII even when I am trying to remove the UII from the investment record.

**Comment by GihaVillazon** [comment] 2017-09-12 19:36
Hi Barry, 

Could you please send over the UIIs through Helpdesk.

Thank You.

**Comment by barrypannell** [comment] 2017-09-12 19:43
The two investments with the issue are: 024-000005664, 024-000007547.

**Comment by GihaVillazon** [comment] 2017-09-12 22:43
Barry, 

Please send over your files.

Thank You.

**Comment by barrypannell** [comment] 2017-09-13 20:21
Sorry.  I mixed up the request for the file with your earlier email. 
[DHS IT Majors BY19 ovw lifecyccost set6 20170911.zip](https://github.com/ombegov/ITDB-schema/files/1300840/DHS.IT.Majors.BY19.ovw.lifecyccost.set6.20170911.zip)

**Comment by GihaVillazon** [comment] 2017-09-13 20:37
Thank you Barry, 

In the future we recommend utilizing the Help Desk for file sharing due to sensitive data. We will analyze the files and get back to you. 

Thank You.

**Comment by barrypannell** [comment] 2017-09-13 20:46
Can I edit a and remove once you pull the file?

**Comment by GihaVillazon** [comment] 2017-09-14 02:36
I edited for you.

Thank You.

**Comment by barrypannell** [comment] 2017-09-14 02:40
Thanks.

Barry Pannell
INVEST Support – OCIO EBMO
MBC Consulting
866-233-9904

**Comment by GihaVillazon** [comment] 2017-09-14 14:56
Hi Barry, 

We have validated it is an issue, due to the essense of time we will recommend the workaround and I have also opened a Jira ticket to have the issue addressed and fixed. 

Workaround is submitting your data without updating the affected investment.

Please do let us know if this creates a another issue or any data integrity concerns.

Thank You.

**Comment by barrypannell** [comment] 2017-09-14 15:21
I did try to remove the offending UII deactivations from the file on Tuesday.  It did not work.  I will try removing them again.  and I will remove the whole section as well.  However in the past, after the initial submission update the validation checks 'related' business case content as being compliant.  IT may still find a UII that should not be there and flag the update. But I will try.

**Comment by barrypannell** [comment] 2017-09-14 18:11
By completely removing the reduced/eliminated investments section from the annual update, the investment update was successful.  Thanks for the work around.  
I assume we still need to 'remove' those investment UIIs from the business case when the validation is updated in ITD.  We would use the monthly submission. Or do you think the monthly submission update of reduced/eliminated investments is okay?

**Comment by barrypannell** [comment] 2017-09-15 18:05
Now that the investment annual submission worked, I tried to use the monthly submission format - 'update eliminated reduced investments' XML to remove the investment UII that does not apply anymore.  
FYI - It did not work.  Same error.

**Comment by GihaVillazon** [comment] 2017-09-15 20:53
Hi Barry, 

Yes both operations will have the same output, therefore the workaround is the best option till we get the validation reassessed.

Thank You.

**Comment by jeremiah-tcg** [comment] 2018-08-01 17:14
Hi Barry, 
With the understanding the system behavior you described still needs to be fixed, can you confirm the investments that started this issue are no longer impacted as a result of our latest deployment?

**Comment by barrypannell** [comment] 2018-08-03 17:09
I have looked in ITD.  The 2 investments at issue had 3 eliminated/reduced investment rows they were trying to remove. (2 for 1 investment and 1 for the other).  2 of the 3 problem rows were removed.  There remains 1 problem row.

**Comment by jeremiah-tcg** [comment] 2018-08-07 16:14
Hi Barry, 
Thanks for looking into this. Can you provide us with the submission file that was used and the error you're receiving? Also, what is the UII associated with the problem row?

**Comment by barrypannell** [comment] 2018-08-10 19:40
I have not tried to remove the remaining issue row since the business logic/rules have not been changed.  I used the data feed report to see the problem rows were removed and I confirmed 2 of 3 were removed.  Do you want me to try to remove the offending eliminated/reduced UII row with an update?  I will send the offending UII and eliminated/reduced UII values in an email.

**Comment by jeremiah-tcg** [comment] 2018-09-06 19:46
Barry and Jeremiah discussed the status of this issue via phone on September 6.  Barry reported it appears the issue is now fixed and recommended we close the issue.

**Closed by jeremiah-tcg** 2018-09-06 19:46 UTC
