### ISSUE TITLE
Get CIO Rating

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#127] opened 2017-08-24 13:53 UTC
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: High
Description of Issue: The Get CIO Rating (through the CIO Rating API) is returning an invalid xml string in the response file. I will email over files soon.

**Comment by GihaVillazon** [comment] 2017-08-24 17:19
Hi Ryan,

Thank You for the files, we are looking into the issue.

**Comment by GihaVillazon** [comment] 2017-08-24 20:17
Hi Ryan,

Have you tried this with another "UII", or "ID" as we are unable to produce the error.

Thank You.

**Comment by rydougherty** [comment] 2017-08-24 20:22
Can you send me your request and response file? I can replicate this issue with every standard investment in my portfolio. I do get valid error messages if a I use a major UII or a bad UII.

**Comment by GihaVillazon** [comment] 2017-08-25 17:29
We need your submission files to try to create the issue, however we are also unable to review the record of intent for submission. 

Thank You.

**Comment by rydougherty** [comment] 2017-08-25 17:42
Giha, Not exactly sure what you mean here. We submitted an AITPS filled with new standard investments with no CIO Rating. When we use the Get File, to try and show that there is no CIO Rating on the Dashboard, we receive an invalid string of xml as the response.  

As a reminder, the first operation used before submitting any data is always the Get Operations. So if there is no data on the Dashboard, the Response still needs to function. So, if the Get file is broken there will be no Submission file.

**Comment by GihaVillazon** [comment] 2017-08-30 20:25
Hi Ryan, 

We do not expect users to run a getCIORating operation for a UII that does not yet have any CIO ratings, but as you pointed the system still needs to respond appropriately if they do. Therefore With the fix in place, the API returns a response with the expected format for getCIORating errors, with a message that no ratings were found.

Thank You.

**Comment by GihaVillazon** [comment] 2017-08-31 20:33
Ryan.

Please explain what is the current issue you are experiencing, as I would like to have one of the developers look into it. 
Please keep in mind IF the issue is not related to the current ticket "Get CIO Rating', please open a new ticket, as it assists in better issue tracking. 

Thank You.

**Comment by rydougherty** [comment] 2017-08-31 20:46
Was this deployed already? In the projects tab, it shows it is pegged for a 9/6 deployment. Briefly testing through Postman, it appears that a standard message has now replaced the server error we were seeing previously.

**Comment by GihaVillazon** [comment] 2017-09-01 00:08
Yes that is correct.
This also addresses your concern discussed during the meeting? If so we will close this ticket.

Thank You.

**Comment by rydougherty** [comment] 2017-09-01 19:56
Can you return blank nodes instead of an error? This would still indicate the investment has no CIO rating on the dashboard.

**Comment by GihaVillazon** [comment] 2017-09-01 19:58
Hi Ryan, 

Having an error message which is clear, seemed to be more user friendly over a blank response. 

Thank You.

**Closed** 2017-10-20 17:16 UTC
