### ISSUE TITLE
Errors and Submission Scenarios 

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#58] opened 2017-07-28 20:08 UTC
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: There are currently two AITPS validation errors that are listed Github, which will prevent Agencies from executing the submission scenarios laid out within the three white-boarding sessions and the following deck released to vendors and the community. 

One error prevents eliminated investments from having either BY or CY funding. And another error prevent new investments from having a Prior UII. Is OMB planning on updating these errors?

**Comment by GihaVillazon-REISys** [comment] 2017-08-01 21:48
Hi Ryan, 

we are unable to reproduce "error prevent new investments from having a Prior UII", could you kindly send over the XML request and response files we would like to retest with the provided data. 

Thank you.

**Comment by murrayalex** [comment] 2017-08-02 12:13
This comment is in reference to the BY19 CPIC Validations List file that was posted two months ago in the draftBY19 folder, not an error that we are currently receiving. We are looking for clarification on whether these rules will be removed for all investments given the new guidance, or if they will be selectively applied for certain investment types.

**Comment by GihaVillazon-REISys** [comment] 2017-08-04 19:20
Hi, 

As we are collecting the information for you, we wanted to share that the prior UII node will be available for new investments. 

Thank you.

**Comment by GihaVillazon** [comment] 2017-08-07 19:29
One error prevents eliminated investments from having either BY or CY funding:
Decision is to exclude amounts by omitting the node altogether.

Thank You.
Giha

**Comment by murrayalex** [comment] 2017-08-07 19:36
This approach does not align with scenario 2b in the presentation that was presented. In that scenario, an eliminated investment would still report PY and CY dollars, and BY would report zero. That situation (based on the validations in place) would result in an Error. 

Are you saying you want us to omit both the BY and CY nodes for eliminated investments? Does that mean Agencies would need to break out costs from both CY and BY into new standard and non-standard investments?

**Comment by ojedanico** [comment] 2017-08-07 19:57
Alex, 
It is recommend but not required by validation for agencies to provide PY and CY figures for a new investment.  

It turned out that it’s better to exclude amounts by omitting the node altogether, as opposed to submitting an empty or null value. The latter approach would have required much more substantial changes to the schema, which requires a numeric value for dollar amounts and doesn’t allow empties or nulls. The omission approach requires very minimal schema changes.
So for example, to submit Total Software Cost when you have amounts for all 3 FYs, you’d do this:
Total Software Cost 100 100 100 
Or if you only have just a BY and a CY amount, you’d omit the PY node like this:
Total Software Cost 100 100 

does this help?

**Comment by ojedanico** [comment] 2017-08-07 19:58
Alex, 
It is recommend but not required by validation for agencies to provide PY and CY figures for a new investment.  

It turned out that it’s better to exclude amounts by omitting the node altogether, as opposed to submitting an empty or null value. The latter approach would have required much more substantial changes to the schema, which requires a numeric value for dollar amounts and doesn’t allow empties or nulls. The omission approach requires very minimal schema changes.
So for example, to submit Total Software Cost when you have amounts for all 3 FYs, you’d do this:
Total Software Cost 100 100 100 
Or if you only have just a BY and a CY amount, you’d omit the PY node like this:
Total Software Cost 100 100 

does this help?

**Comment by murrayalex** [comment] 2017-08-07 20:05
Hey Nico,
No, and I may not be explaining this properly. So my concern is with the investments marked Eliminated in scenario 2b. There are current validation errors on the ITDB that prevent you from submitting an investment marked as eliminated if you are providing values for CY and BY. Based on scenario 2b, OMB is suggesting that we should be able to do just that (providing values for CY). I am trying to reconcile the suggested approach in the scenario slides with the validation errors posted to github.

**Comment by ojedanico** [comment] 2017-08-07 20:17
If its marked as eliminated you should have not have a value for BY since its being eliminated. Are you getting an error when you put in $0 for the BY19 amount?

**Comment by murrayalex** [comment] 2017-08-07 20:49
If I set my investment up as is suggested in Scenario 2b (funding in PY and CY, zero funding in BY), then I receive the following - Error: BY and CY amounts must be zero for eliminated investments

It is the CY funding that I have a question about, and whether this validation error will be updated/removed so that we can follow the suggested scenarios. Do you want to hop on a call tomorrow morning to discuss further?

**Comment by ojedanico** [comment] 2017-08-07 20:53
That should be the issue - let me have our dev team look into the error and I will get back to you tomorrow.

**Comment by ojedanico** [comment] 2017-08-08 20:53
We are currently updated this validation to correct the error - it will be deployed Aug 14th.

**Comment by murrayalex** [comment] 2017-09-11 20:02
Hey Nico,

We have had a couple of Agencies run into this issue again, and I am able to recreate it myself. When I try to submit an eliminated investment with dollars in PY and CY (not BY), I receive the following error:

`Error: BY and CY amounts must be zero for eliminated investments`

This error was removed several weeks ago, but appears to be back. Can you please take a look ASAP? This is causing a lot of confusion. I will send over a file shortly.

**Comment by ojedanico** [comment] 2017-09-11 20:09
looking in to it now

**Comment by ojedanico** [comment] 2017-09-11 20:33
We will fix for Presidential budget submission since our window is closing in an 1.5 hrs. for the work around just have them put zero in FY19 and we can eliminate on the backend.

**Comment by murrayalex** [comment] 2017-09-11 20:46
Thanks, Nico. Can you please communicate this to the desk officers for their awareness?

**Comment by TsitsiL** [comment] 2018-03-16 18:17
closing this ticket as it was resolved in #218

**Closed by TsitsiL** 2018-03-16 18:17 UTC
