### ISSUE TITLE
SIR Submission Error - Priority: High

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#135] opened 2017-08-28 19:16 UTC
Hello!

I wasn't getting this error before, but now when I submit an SIR, I get the following error:

Error 1845: Element '{http://www.itdashboard.gov/service}towers': No matching global declaration available for the validation root. on line 4

I'm sure it just has something to do with the format of my input file.  I can send the input file to you if you'd like, just let me know.

**Comment by GihaVillazon** [comment] 2017-08-28 19:50
Hi Courtney, 

If you need us to look at the file, we can however if you are not getting the error anymore and by correcting the input it resolved, there is no need to further analyze. 

Thank You.

**Comment by courtneycorwin** [comment] 2017-08-29 18:08
I will send you my file, but please tell me what this error means.

I was not getting it last week, it's a new error and I'd like to know what's causing it.  Please don't close this until I can submit successfully.

**Comment by GihaVillazon** [comment] 2017-08-29 20:19
Hi Courtney, 

Please send us the files we will certainly take a look at the error you are receiving . 

Thank You.

**Comment by courtneycorwin** [comment] 2017-08-29 20:20
I sent it at 2:14 with a high priority mark.

**Comment by courtneycorwin** [comment] 2017-08-30 17:02
I know you guys are super busy, but can I get an ETA on when you can help me to resolve this error?  It's prohibiting us from testing SIRs at all at this point.

**Comment by courtneycorwin** [comment] 2017-08-30 18:17
I've removed all attributes from the "towers" tag and now I'm getting this error:

Error 1845: Element 'towers': No matching global declaration available for the validation root. on line 4 - slightly different from the original error, but not my much.

I really need someone to respond and tell me what this error means. Testing has been halted since Monday.

**Comment by GihaVillazon** [comment] 2017-08-30 18:27
Hi Courtney, 

I am having the developers look into this as we speak. Will keep you posted. 

Thanks for your patience.

**Comment by GihaVillazon** [comment] 2017-08-30 18:43
Would you please send the response file. 

Thank You.

**Comment by courtneycorwin** [comment] 2017-08-30 18:48
Sent.

**Comment by GihaVillazon** [comment] 2017-08-30 19:08
Hi Courtney, 

Please try once again after removing the below tag from your submission file.
xmlns='https://itdashboard.gov/service'

Thank You.

**Comment by GihaVillazon** [comment] 2017-08-30 22:20
Hi Courtney, 

Circling back to ensure the problem was resolved, I hope you are able to continue with your testing. 
Let us know as we would like to close the ticket, or further investigate the root cause. 

Thank You.

**Comment by courtneycorwin** [comment] 2017-08-30 22:32
Sorry that I didn't respond sooner - I didn't get an email notification regarding your post 3 hours ago.  I did that - same error.  I removed all attributes from the "towers" tag and still go the same error.

**Comment by courtneycorwin** [comment] 2017-08-31 01:17
I've just sent the ITDB input, output, and error files for your review so you can see the results for yourself.

**Comment by courtneycorwin** [comment] 2017-08-31 11:54
Hi guys, do we need to do a webex or something?  Have you been able to replicate the error using my input file?

**Comment by GihaVillazon** [comment] 2017-08-31 15:58
Hi Courtney, 

I will get back to you, I'm having the development team look into this issue. 

Thank You.

**Comment by GihaVillazon** [comment] 2017-08-31 19:02
Hi Courtney, 

The developers have been unable to reproduce the problem with the test file you have submitted. They have tried both on test servers and UAT itself. Further, they noted that the response file provided contains XMLNS notation and a namespace prefix to the elements, which is not something our system should produce by default. Our suspicion is that the submission file may contain an xml namespace attribute which is not compatible with this submission type. May I ask you to resubmit your data with a new submission file, and see if the error is still occurring.

Thank You.

**Comment by courtneycorwin** [comment] 2017-08-31 19:08
Hi Giha,

Thanks for the update.  I have a couple of issues with this response:

1.  As of Thursday 8/24, we were able to validate SIRs with no issues.  On Monday the 28th, after the site update, we could not.

2.  I tried a file with no attributes (no validateOnly tag, no namespaces, etc), including the xml namespace and got the same result.  I sent those results to you yesterday.

We're obviously still trying to work through this, but it's extremely difficult to troubleshoot this on our side especially when you can't tell me what this error means.

**Comment by GihaVillazon** [comment] 2017-08-31 20:19
Hi Courtney, 

Sorry for the disconnect, however as discussed in the meeting could you please submit your file and record the time, one of my developers will analyze the submission.

Thank You.

**Comment by courtneycorwin** [comment] 2017-08-31 20:21
As murphy's law would have it, the site that I've been testing from is down.  We're just waiting for access to be restored and then I'm gonna flood you with files :)

**Comment by GihaVillazon** [comment] 2017-08-31 20:30
haha no worries, appreciate your patience. 
keep us posted please.

**Comment by GihaVillazon** [comment] 2017-08-31 22:15
Hi Courtney, 

Just to verify When submitting a SIR via API, the URL to use is /api/v1/investmentreport not /api/v1/businesscase, and when submitting SIR via web, the button to check is "Standard Investment Report" not "Business Case". 
You are following the above to submit SIRs via API correct?

Thank You.

**Comment by courtneycorwin** [comment] 2017-08-31 22:17
I am 91% sure that yes, we are.  But I will have a firm answer for you by morning.

**Comment by GihaVillazon** [comment] 2017-08-31 23:09
We will wait for your confirmation. 

Thank You.

**Comment by courtneycorwin** [comment] 2017-09-01 07:47
Ok - apparently that suggestion was enough to point us in the right direction.  We've made several updates that will be tested this morning, but it looks promising!!  THANKS!

**Comment by GihaVillazon** [comment] 2017-09-01 13:20
Excellent, thank you for confirming I will close this ticket now.

**Comment by courtneycorwin** [comment] 2017-09-01 13:21
oh, we haven't solved the problem yet - we're still testing.

**Closed by GihaVillazon** 2017-09-01 13:20 UTC

**Comment by courtneycorwin** [comment] 2017-09-01 14:40
Ok - we've still got some kinks to work out, but I think we're good.  Thanks!!

**Comment by ojedanico** [comment] 2017-09-07 17:11
Reference Jira Ticket 882 - in case this is still an issue

**Comment by courtneycorwin** [comment] 2017-09-07 17:19
I will -I think we're good though.  We ended up just rebuilding our getInvestment call.  I REALLY appreciate your attention to the issue though!
