### ISSUE TITLE
SIR Projects Submissions- Funded By TMF or IT WCF

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#283] opened 2018-08-01 20:39 UTC
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: We are receiving a server error following if `<fundedBy>` contains N/A. The server error goes away when I send a different value for `<fundedBy>`

Request 1: 
`<?xml version="1.0" encoding="UTF-8"?>
<towers validateOnlyIndicator="true">
  <tower>
    <operation>add</operation>
    <towerDetails>
      <UII>011-200003533</UII>
    </towerDetails>
    <investmentCostDetails>
      <investmentCostDetail>
        <category>1</category>
        <PY>0.018000</PY>
        <CY>0.019000</CY>
        <BY>0.020000</BY>
      </investmentCostDetail>
      <investmentCostDetail>
        <category>2</category>
        <PY>0.000180</PY>
        <CY>0.000190</CY>
        <BY>0.000200</BY>
      </investmentCostDetail>
      <investmentCostDetail>
        <category>3</category>
        <PY>0.180000</PY>
        <CY>0.190000</CY>
        <BY>0.200000</BY>
      </investmentCostDetail>
      <investmentCostDetail>
        <category>4</category>
        <PY>0.018000</PY>
        <CY>0.019000</CY>
        <BY>0.020000</BY>
      </investmentCostDetail>
      <investmentCostDetail>
        <category>5</category>
        <PY>0.018000</PY>
        <CY>0.019000</CY>
        <BY>0.020000</BY>
      </investmentCostDetail>
      <investmentCostDetail>
        <category>6</category>
        <PY>0.018000</PY>
        <CY>0.019000</CY>
        <BY>0.020000</BY>
      </investmentCostDetail>
      <investmentCostDetail>
        <category>7</category>
        <PY>0.018000</PY>
        <CY>0.019000</CY>
        <BY>0.020000</BY>
      </investmentCostDetail>
    </investmentCostDetails>
    <projects>
      <project>
        <operation>add</operation>
        <uniqueProjectID>B</uniqueProjectID>
        <projectName>Wireless Acceleration</projectName>
        <objective>Accelerated success</objective>
        <projectStartDate>2011-04-14</projectStartDate>
        <projectCompletionDate>2016-10-11</projectCompletionDate>
        <lifeCycleCost>2.4</lifeCycleCost>
        <SDLCMethodology>2</SDLCMethodology>
        <releaseEverySixMo>N/A</releaseEverySixMo>
        <releaseEverySixMoComment>test</releaseEverySixMoComment>
        <productionDeploymentDate>07/11/2018</productionDeploymentDate>
        <fundedBy>N/A</fundedBy>
        <commercialSolutionsCosts>3</commercialSolutionsCosts>
        <commercialSolutionsAdoption>1</commercialSolutionsAdoption>
        
        <activities>
          <activity>
            <operation>add</operation>
            <isAgile>Y</isAgile>
            <releaseName>tEST245</releaseName>
            <releaseNumber>num 1000</releaseNumber>
            <releaseDescription>Description</releaseDescription>
            <NPI>4</NPI>
            <NPE>2.0</NPE>
            <NCE>3.0</NCE>
            <NCI>1</NCI>
            <DTC>4.0</DTC>
            <DPC>5.0</DPC>
            <startDatePlanned>2018-08-01</startDatePlanned>
            <startDateActual>2018-08-01</startDateActual>
            <completionDatePlanned>2018-08-03</completionDatePlanned>
            <completionDateProjected>2018-08-03</completionDateProjected>
            <completionDateActual>2018-08-03</completionDateActual>
            <totalCostPlanned>1</totalCostPlanned>
            <totalCostProjected>1</totalCostProjected>
            <totalCostActual>0.003</totalCostActual>
          </activity>
        </activities>
      </project>
    </projects>
  </tower>
</towers>`

Response:
`{
    "ok": false,
    "error": true,
    "metadata": null,
    "httpStatusCode": 500,
    "httpStatusMessage": "Internal Server Error",
    "responseTime": 0.077962875366211,
    "result": null,
    "errors": [
        {
            "code": 8,
            "message": "Undefined index: projectID",
            "severity": 0,
            "file": "/services/sEgvHttpP/server/20/htdocs/api/Pittsburgh/Controllers/ITDB2/InvestmentReport.php",
            "line": 1023
        }
    ]
}`

Valid Request:
See Issue #282

**Comment by jeremiah-tcg** [comment] 2018-08-08 14:32
Hi Ryan, 
We believe the cause was a missing field in one of our post processes. This should be resolved once we deploy our 2018.08A build to UAT this week.

**Comment by jeremiah-tcg** [comment] 2018-08-16 02:38
Hi Ryan, 
2018.08A was deployed on 8/12. May we close this ticket?
Regards, 
Jeremiah

**Closed** 2018-08-23 18:07 UTC
