### ISSUE TITLE
Submission Confirmation - Validation vs Submission

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#322] opened 2018-08-30 13:14 UTC
Hi All,

I tested a Submission Confirmation today (I don't have a valid ITPS submitted).  When I sent it up with validateOnly=true, the response back was that the confirmation was successful.  When I sent it up with validateOnly=false, the response back listed a few errors.  

Since users only get one chance to submit a Submission Confirmation once it's successful, the validation should return the same errors.

I'll send my files to the support email.  Thanks!

**Comment by jeremiah-tcg** [comment] 2018-08-30 15:27
Hi Courtney, 
We created ITD-1954 to look into this. Will circle back with you when we've found the cause.
Regards, 
Jeremiah

**Comment by jeremiah-tcg** [comment] 2018-08-31 23:47
Hi Courtney, 
We deployed 2018.09A which included a fix for this. Please let me know if we can close this issue.
Regards, 
Jeremiah

**Comment by courtneycorwin** [comment] 2018-09-04 12:41
Hi All,

I tested this, and I'm not sure whether to close it or not.  I accidentally submitted a blank file which got a successful response.  And then I submitted my actual test ITPS (which got an failed response as expected).  The confirmation got a successful response on both validation and submission, but I'm guessing that's against the blank ITPS?  

Anyway - I think this will be one of those things that I need to observe throughout submission - particularly to see how it works after the business cases, SIRs, etc are submitted before I feel comfortable closing it.

**Comment by jeremiah-tcg** [comment] 2018-09-04 15:02
Hi Courtney, 

With our push of 2018.09A to UAT on Friday, the locking of the submissions functionality is now hooked up with the submission confirmation process. Sending a submissionConfirmation with validateOnlyIndicator=false  will now lock the windows for itBudget if one was already sent, even if it was blank. The blank file submitted added Eliminated by Omission records for FY19 records in FY20. 

We looked at the submissionConfirmation table and see that there is stage1 record for USDA which means a submissionConfirmation file with validatenblyIndicator=false was sent after FY20 an itBudget submission. So, now if  a second submissionConfirmation file is sent, you will see the errors related to the Portfolio Details which would be about required files that haven't been sent yet. If you send all the required data, then the second submitted submissionConfirmation file with validatenblyIndicator=false will create stage2 and lock the Portfolio Detail window.

We can reset this by removing the submissionConfirmation file to reopen the itBudget submission window if you'd like to test it some more Please let us know.

Regards, 
Jeremiah

**Comment by courtneycorwin** [comment] 2018-09-04 15:16
Yes - please reset that.  I thought that you weren't locking the submissions in UAT?

**Comment by jeremiah-tcg** [comment] 2018-09-04 20:08
Hi Courtney,
This has been reset.  Given we were aiming to release 2018.09A as early as possible and the remaining development work that was needed to complete the submission confirmation process during that sprint, we released the functionality without giving much thought to its effect. We recommend agencies  and vendors set validateOnlyIndicator=true when testing this feature in the future and apologize for any inconvenience this may have caused.
Regards, 
Jeremiah

**Comment by jeremiah-tcg** [comment] 2018-09-14 16:34
Per our discussion at the 9/13 CPIC Vendor meeting, closing this issue.

**Closed by jeremiah-tcg** 2018-09-14 16:34 UTC
