### ISSUE TITLE
Data Center IDs

### ISSUE THREAD

**Issue by bill-gehrke-hhs** [ombegov/ITDB-schema#325] opened 2018-09-04 17:35 UTC
It appears that the list of data center IDs has been updated in the Data Dictionary and Enumerations spreadsheet.  However, in UAT, we are receiving the following warning:

000182-ITP: Data Center ID 'DCOI-DC-574493' was not found in the agency's Data Center Inventory.

This data center is in the list of Data Centers (row 11499) but is still receiving the warning.  Additionally, old data centers that were valid for FY19 but are no longer valid are not receiving the warning.  This is why I suspect the list may not have been updated.  Could you confirm whether the UAT site has the current list of data centers, and, if not, when this will be updated?  Fortunately, since it is a warning, it does not affect testing, but it does become a concern for submission to see incorrect information about what is and is not in the inventory.

**Comment by jeremiah-tcg** [comment] 2018-09-04 20:12
Hi Bill, 
We will need to pull in the data into UAT for this to be resolved. Its currently hooked up in production, but hasn't been loaded into UAT. This is ITD-1967 which we estimate will be deployed within the next couple of days.
Regards, 
Jeremiah

**Comment by jeremiah-tcg** [comment] 2018-09-05 16:17
Hi Bill, 
ITD-1967 was deployed to UAT. Please let us know if the issue is now resolved for you.
Regards, 
Jeremiah

**Comment by bill-gehrke-hhs** [comment] 2018-09-05 16:54
This seems to be partially resolved in that I am no longer receiving warnings related to newly-added codes.  However, I will note that if I provide an old code (for example DCOI-DC-534365) that is no longer listed in the Data Dictionary & Enumerations (because it is no longer a valid record in our latest IDC submission,) I do not receive a warning, which suggests that the old values may still be active in UAT.  

Note that if I try a made-up code (DCOI-DC-934365 for example,) I do get a warning, so the warning is functioning.

**Comment by jeremiah-tcg** [comment] 2018-09-06 15:18
Hi Bill, 
After further review, validation 000182-ITP checks whether the data center ID exists rather than checking if it exists AND is a validFacility=Y. We will need to confirm the correct behavior with OMB; however, this does not appear to be something that will be corrected by the September 10 submission. Please let me know if you have questions.
Regards, 
Jeremiah

**Comment by jeremiah-tcg** [comment] 2018-10-09 17:12
The Data Dictionary was updated with the same Data Center IDs referenced the IT Dashboard. I am closing this ticket as a result.

**Closed by jeremiah-tcg** 2018-10-09 17:12 UTC
