### ISSUE TITLE
Invalid Value Returned by analysisConclusion for successful submission

### ISSUE THREAD

**Issue by kengineer** [ombegov/ITDB-schema#188] opened 2017-09-15 20:25 UTC
We just submitted our annual Major Business Case and noticed that the XML response returned for analysisConclusion, which is expected to be an integer 1-5, is actually the string value submitted for analysis result. Below is a snippet of the offending XML from the response (issue around line 470). Notice that analysisResult and analysisConclusion have the same value. The full response is attached. This causes a problem when trying to deserialize the XML on our end.

`<businessCase-response:operationalAnalysis>
              <businessCase-response:dateOfAnalysis>2016-09-26</businessCase-response:dateOfAnalysis>
              <businessCase-response:analysisResults>STAQS continues to benefit ...</businessCase-response:analysisResults>
              <businessCase-response:analysisConclusion>STAQS continues to benefit...</businessCase-response:analysisConclusion>
            </businessCase-response:operationalAnalysis>`

**Comment by GihaVillazon** [comment] 2017-09-15 20:43
Hi,

We are aware of this concern and have the fix in place which will be deployed with 09B. Your data is being saved. The issue is only with the response operation not retrieving the data correctly from our database. The fix will be on this operation.

Thank You.

**Comment by TsitsiL** [comment] 2017-09-15 22:10
This issue was previously reported in GitHub #173, in which we are addressing a fix for the response operation. Closing this issue as it is a duplicate of an existing one.

**Closed by TsitsiL** 2017-09-15 22:10 UTC
