### ISSUE TITLE
getInvestment returns Operational Analysis Result in Analysis Conclusion field

### ISSUE THREAD

**Issue by bill-gehrke-hhs** [ombegov/ITDB-schema#173] opened 2017-09-11 15:13 UTC
Using getInvestment for HHS, the businessCase-response:analysisResults and businessCase-response:analysisConclusion are both returning the data submitted in the results field.  The expected value for the Analysis Conclusion would be a value from 1-5, rather than the text of the Results.

**Comment by GihaVillazon** [comment] 2017-09-11 15:41
Hi Bill, 

As we are looking into this, would you please send over your submission files. 

Thank You.

**Comment by TsitsiL** [comment] 2017-09-11 15:57
Hi Bill,

This issue was reported by another agency last week and we looked into it and found that the values from the input file are being saved correctly in our database. The issue is with the operation that retrieves this data to display in the response. So the response itself has to be fixed – we will do so in the next available sprint. Again, I will reiterate that the inputs get saved properly in our database, so the data you enter for MITBC submissions  from today onwards will be saved. We just need to update the response to accurately reflect what was saved for each element.

Please let me know if you have any questions.

Thanks!

**Comment by rydougherty** [comment] 2017-10-17 17:43
Hi Tsitsi, I notice this is still an issue. Did the data reconciliation effort push back work on this issue? If so, do you have a time frame on when this issue will be resolved?

**Comment by TsitsiL** [comment] 2017-10-17 20:07
Hi Ryan,
I have asked the team to look into this. We had a deployed a fix for this september, I am looking into what happened and will get back to you when I know more.

Thanks!

**Comment by TsitsiL** [comment] 2017-10-18 13:58
Good morning Ryan,
I found out that the deployment of this fix in September was erroneously reverted and it needs to be re-deployed. We expect to do so COB on Monday October 23 in a Hotfix. I apologize for the inconvenience, but the fix will be in time for the monthly submissions.

Please let us know if you have any questions.

Thanks!

**Comment by rydougherty** [comment] 2017-10-18 14:12
Thanks Tsitsi, that works for us.

**Closed** 2017-12-04 20:39 UTC
