### ISSUE TITLE
IT Dashboard Prevents Add Application Submission

### ISSUE THREAD

**Issue by rydougherty** [ombegov/ITDB-schema#284] opened 2018-08-01 20:54 UTC
Name: Ryan Dougherty
Organization: Booz Allen, supporting eCPIC PMO
Urgency: Medium
Description of Issue: We are receiving the following error when attempting to submit an Add operation for an Application Investment: `<error>000872-SIR: The operation addDelivery is not available at this time.</error>`

I double checked that the UII we are submitting for is marked as Application (08) in the AITPS.

Request: 
`<?xml version="1.0" encoding="UTF-8"?>
<towers validateOnlyIndicator="true">
  <tower>
    <operation>add</operation>
    <towerDetails>
      <UII>011-002866003</UII>
    </towerDetails>
    <investmentCostDetails>
      <investmentCostDetail>
        <category>Application Development</category>
        <PY>0.003000</PY>
        <CY>0.003000</CY>
        <BY>0.045000</BY>
      </investmentCostDetail>
      <investmentCostDetail>
        <category>Application Support and Operations</category>
        <PY>0.000000</PY>
        <CY>0.000000</CY>
        <BY>0.000000</BY>
      </investmentCostDetail>
      <investmentCostDetail>
        <category>Business Software</category>
        <PY>0.000000</PY>
        <CY>0.000000</CY>
        <BY>0.008000</BY>
      </investmentCostDetail>
    </investmentCostDetails>
    <projects>
      <project>
        <operation>add</operation>
        <projectID>5637</projectID>
        <uniqueProjectID>A</uniqueProjectID>
        <projectName>Infrastructure Transition</projectName>
        <objective>Success</objective>
        <projectStartDate>2010-07-01</projectStartDate>
        <projectCompletionDate>2016-10-03</projectCompletionDate>
        <lifeCycleCost>1.206</lifeCycleCost>
        <SDLCMethodology>2</SDLCMethodology>
        <releaseEverySixMo>Yes</releaseEverySixMo>
        <releaseEverySixMoComment>No further comments</releaseEverySixMoComment>
        <productionDeploymentDate>08/01/2018</productionDeploymentDate>
        </project>
    </projects>
  </tower>
</towers>`

**Comment by austin-moffa** [comment] 2018-08-03 14:13
This will be fixed in the current sprint (08A) by tickets 1882/1884.

**Comment by jeremiah-tcg** [comment] 2018-08-16 02:38
Hi Ryan, 
Both tickets were deployed on 8/12. Can you confirm the issue is resolved?

**Closed** 2018-08-23 18:07 UTC
