### ISSUE TITLE
AITPS New Investemnt and Prior UII Validation 

### ISSUE THREAD

**Issue by barrypannell** [ombegov/ITDB-schema#311] opened 2018-08-22 16:05 UTC
Name: Barry Pannell
•Organization: MBC/DHS Support
•Urgency: Medium
•Description of Issue: 
DHS is attempting to add a new investment with UII 024-000005262 on the IT Portfolio submission.  It is being rejected as a 'new' with a message the UII appears to be reused from a prior year.  When I change it to a 'no change' status and provide prior UII, it is rejected because 'there was no previous investment with that UII'. 
This investment was drafted and submitted last September for BY19 with the UII.  But the funding was delayed till this year after passback and the investment was removed from the final BY19 AITPS in January.  So it was never a funded investment as part of the DHS AITPS President's Budget submission.  
It appears the department cannot use the UII even though it e=was never a part of a 'final' AITPS. 

I would have thought that since the UII was never part of the final president's budget submission that it could be used this year when the same investment is now funded.

**Comment by jeremiah-tcg** [comment] 2018-08-23 17:14
Hi Barry, 

We think we've identified the cause and are discussing a fix that involves modifying a trigger on one of the validations. I will provide an expected deployment date once we've ironed out the details.

Regards, 
Jeremiah

**Comment by jeremiah-tcg** [comment] 2018-08-31 23:58
This is ITD-1955 for internal tracking

**Comment by jeremiah-tcg** [comment] 2018-09-10 03:06
Hi Barry, 
We deployed 2018.09B to UAT and production that included a fix for this. Please let me know if we can close this issue.
Regards, 
Jeremiah

**Comment by jeremiah-tcg** [comment] 2018-09-14 16:34
Per our discussion at the 9/13 CPIC Vendor meeting, closing this issue.

**Closed by jeremiah-tcg** 2018-09-14 16:34 UTC
