### ISSUE TITLE
Performance Metrics - CY Target Values

### ISSUE THREAD

**Issue by courtneycorwin** [ombegov/ITDB-schema#321] opened 2018-08-29 18:24 UTC
Priority: HIGH

Hi All,

It looks like the CY targets weren't cleared out.  Based on my getInvestment response, it looks like for every performance metric the PY and CY targets are the same.  So, when we send up a new value for the CY target (for the first time), we're getting an error that once a CY target is submitted it can't be changed without a rebaseline.

**Comment by elliotyoon202** [comment] 2018-08-29 18:54
Hi Courtney,

We'll circle back with an ETA for this. 

ITD-1953 (Internal Tracking)

**Comment by jeremiah-tcg** [comment] 2018-08-30 16:53
Hi Courtney, 
We've identified the cause and are working on implementing a fix for it now. 
Regards, 
Jeremiah

**Comment by jeremiah-tcg** [comment] 2018-08-31 23:48
Hi Courtney, 
We deployed 2018.09A to UAT which included a fix for this. Please us know if the issue is now resolved.
Regards, 
Jeremiah

**Comment by courtneycorwin** [comment] 2018-09-04 13:05
Validated - thanks!

**Closed** 2018-09-04 14:06 UTC
